---
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/15.yaml

packages:
- .

extra-deps:
  - git: https://github.com/fmidue/output-monad.git
    commit: 1f3edf2cd4a13ca6cb62e24a57f6da66ef6894d0
    subdirs:
      - output-monad
